server.port: 80

spring.datasource:
  url : jdbc:postgresql://localhost:5432/ecomm
  username: postgres
  password: ENC(t0ADr6e0/4nZxomqfQCWRK2oIKgUIWO3)

spring.jpa:
  show-sql: true
  generate-ddl: true
  allowed.origins: http://localhost:4200
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate:
    ddl-auto: update
    #spring.sql.init.mode=always